dataset: "D:/GitHub/datasets/crack-detection"

use_gpu: 1

max_epochs: 2
batch_size: 16

optimizer:
  lr: 0.001
  momentum: 0.9

scheduler:
  step_size: 1
  gamma: 0.5

training:
  train_percent_check: 0.01
  val_percent_check: 0.01
  test_percent_check: 0.01